[build-system]
requires = ["setuptools>=45",
            "setuptools_scm[toml]>=6.2",
            "wheel"]
build-backend = 'setuptools.build_meta'

[project]
name = "gdctb_craft"
description = "A Python package to process and analyze data from the GDCTB craft instrument."
readme = "README.rst"
dynamic = ["version"]
authors = [{name = "Andrew Robbertz", email="andrew.l.robbertz@nasa.gov"}]
license = {file = "LICENSE.rst"}
requires-python = ">=3.12"
keywords = ["nasa mission", "space weather"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache 2.0",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
  'astropy>=4.1.0',
  'numpy>=1.16.0',
  'swxsoc @ git+https://github.com/swxsoc/swxsoc.git@main',
]

[project.optional-dependencies]
dev = [
  "gdctb_craft[docs,test,style]"
]

docs = [
  'sphinx',
  'sphinx-automodapi',
  'pydata-sphinx-theme',
]

test = [
  'pytest',
  'pytest-astropy',
  'pytest-cov',
  'coverage[toml]'
]

style = ['ruff']

[tool.setuptools.package-data]
"gdctb_craft.data" = ["**"]

[tool.setuptools]
packages = ["gdctb_craft"]

[tool.setuptools_scm]
write_to = "gdctb_craft/_version.py"

[tool.pytest.ini_options]
testpaths = [
   "gdctb_craft/tests",
   "docs"
]
doctest_plus = "enabled"
text_file_format = "rst"
addopts = "--doctest-rst"

[tool.coverage.run]
omit = [
  'gdctb_craft/__init*',
  'gdctb_craft/conftest.py',
  'gdctb_craft/*setup_package*',
  'gdctb_craft/tests/*',
  'gdctb_craft/*/tests/*',
  'gdctb_craft/extern/*',
  'gdctb_craft/version*',
  '*/gdctb_craft/__init*',
  '*/gdctb_craft/conftest.py',
  '*/gdctb_craft/*setup_package*',
  '*/gdctb_craft/tests/*',
  '*/gdctb_craft/*/tests/*',
  '*/gdctb_craft/extern/*',
  '*/gdctb_craft/version*',
]

